server:
  port: 8081

gg:
  jte:
    developmentMode: true
    templateLocation: src/main/resources/jte

spring:
  application:
    name: m-crm

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true



