server:
  port: 8081

gg:
  jte:
    developmentMode: true
    templateLocation: src/main/resources/jte

spring:
  application:
    name: mentee-power-crm

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.yourcompany.backendcore: DEBUG



