name: CI
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Tests
        run: ./gradlew --no-daemon test
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;MODE=PostgreSQL
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: ''
          SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect

      - name: JacocoTestReport
        run: ./gradlew --no-daemon jacocoTestReport

      - name: JacocoTestCoverage
        run: ./gradlew --no-daemon jacocoTestCoverageVerification

      - name: build
        run: ./gradlew --no-daemon build